### ISSUE TITLE
No se puede borrar mientras se escribe en el vértice

### ISSUE THREAD

**Issue by EyderACM** [Shadic78/Proyecto-Matematicas-Discretas-Grafos#1]

**Comment by EyderACM** [comment]
No es posible borrar después de escribir un caracter en el vértice.
Explorador utilizado: Firefox.

**Comment by Shadic78** [comment]
En navegadores no funcione el borrar el nombre, pero de manera local con processing 3 sí funciona

**Comment by EyderACM** [comment]
Va :)
